---
- hosts: all
  become: true
  roles:
    - eval2-backend
  vars_files:
    - /home/coderbob/Desktop/code-platoon/roles/roles-secret.yml
    - /home/coderbob/Desktop/code-platoon/roles/misc/main.yml
  vars: 
    ansible_user: "ubuntu"
    ansible_ssh_private_key_file: "/home/coderbob/Downloads/cpdevopsew-us-east-2.pem"